### ISSUE TITLE
歪个楼，楼主真的是高中生吗？

### ISSUE THREAD

**Issue by BruceZhaoR** [wfjsw/OrzNamer-nodejs#1]
简直是刷新我的世界观。。 :astonished:

**Comment by wfjsw** [comment]
Not related.

----
Join us at https://orz.chat/

**Comment by BruceZhaoR** [comment]
:six: 的飞起，能带上我飞吗？

**Comment by BruceZhaoR** [comment]
怎么没有readme 看不懂这是一个什么项目

**Comment by wfjsw** [comment]
用于 Telegram 炒鸡群改名的一个项目  现在是 ##Orz 自用 没什么参考意义（逃

**Comment by BruceZhaoR** [comment]
已经加入群聊了  哈哈  :blush:

**Comment by wfjsw** [comment]
来Telegram吧 可能好看一点 https://telegram.org

**Comment by BruceZhaoR** [comment]
刚看里那个汉化的 organisation ，感觉功能好强大。 我之前用的是 slack。
